name: Test Pipeline
on:
  push:
    branches:
      - '*'
      - '!main'
  workflow_call:

jobs:
  test_app:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip setuptools
          python -m pip install --quiet pylint
          python -m pip install --quiet pytest
          python -m pip install --quiet bandit
          python -m pip install .
      - name: Run Tests
        run: |
          pytest tests/test_app.py

      - name: Lint check
        run: pylint app/

      - name: Security check
        run: bandit -lll --configfile bandit.conf --recursive app/
